ex1_kakas/config/routes.rb
Rails.application.routes.draw do
  resources :products
  root "products#index"

end

ex1_kakas/app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, presence: true
  validates :price, presence: true, numericality: true
end

ex1_kakas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ex1_kakas/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @products = Product.all #給_index.html.erb用
    @product = Product.new(product_params)

    if @product.save
      render "success"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @products = Product.all
    @product = Product.find(params[:id])

    if @product.update(product_params)
      render "success"
    else
      render :edit
    end
  end

  def destroy
    @products = Product.all
    @product = Product.find(params[:id])
    @product.destroy
    render "success"
  end

  private
  def product_params
    params.require(:product).permit(:title, :price)
  end
end

ex1_kakas/app/helpers/application_helper.rb
module ApplicationHelper
end

ex1_kakas/app/helpers/product_helper.rb
module ProductHelper
end

ex1_kakas/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KakasAJAX</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ex1_kakas/app/views/products/_edit.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>Edit <%= @product.title %></h3>
    </div>
    <%= render "form" %>
  </div>
</div>

ex1_kakas/app/views/products/_form.html.erb
<%= bootstrap_form_for @product, remote: true do |f| %>
  <div class="modal-body">
    <%= f.text_field :title %>
    <%= f.text_field :price %>
  </div>
  <div class="modal-footer">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "取消", "#", class: "btn btn-default",
                            data: { dissmiss: "modal" } %>
  </div>
<% end %>

ex1_kakas/app/views/products/_index.html.erb
<% @products.each do |product| %>
  <tr>
    <td><%= product.title %></td>
    <td><%= product.price %></td>
    <td><%= link_to "Edit", edit_product_path(product),
                            remote: true, class: "btn btn-primary" %></td>
    <td><%= link_to "Delete", product_path(product), method: :delete,
                              remote: true, class: "btn btn-danger",
                              data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>

ex1_kakas/app/views/products/_new.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h3>New Product</h3>
    </div>
    <%= render "form" %>
  </div>
</div>

ex1_kakas/app/views/products/edit.js.erb
$("#product-modal").html("<%= j render "edit" %>")
$("#product-modal").modal("show")

ex1_kakas/app/views/products/index.html.erb
<div class="container">
  <div class="well">
    <!-- link_to 加上 remote: true 就是跟 rails 說這個地方我們要使用 AJAX -->
    <!-- 像這裡他在跑完 new action 之後，就會去找 new.js.erb 檔 -->
    <%= link_to "New Product", new_product_path, remote: true, class: "btn btn-primary" %>
  </div>
</div>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <td>Edit</td>
      <td>Delete</td>
    </tr>
  </thead>

  <tbody class="product-index">
    <%= render "index" %> <!-- tbody 裡就是資料會變動的地方，資料變動時只重新載入此處 -->
  </tbody>
</table>

<!-- 跳出視窗：我們可以利用 AJAX 跟 JavaScript 塞東西到裡面去 -->
<!-- 譬如要 Edit Product，我們就可以塞 Edit 的 form 到這裡 -->
<div id="product-modal" class="modal fade"></div>

ex1_kakas/app/views/products/new.js.erb
// 把 _new.html.erb 內容塞到 modal 裡，j 是 escape_javascript 的 sugar 語法
$("#product-modal").html("<%= j render 'new' %>")

// 讓 modal 跳出來
$("#product-modal").modal("show")

ex1_kakas/app/views/products/success.js.erb
$(".product-index").html("<%= j render 'index' %>")

// 把modal隱藏起來
$("#product-modal").modal("hide")